language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

env:
  - XHGUI_SAVE_HANDLER=mongodb
  - XHGUI_SAVE_HANDLER=pdo XHGUI_PDO_DSN="mysql:host=localhost;dbname=xhgui" XHGUI_PDO_USER=root

jobs:
  allow_failures:
    - php: 7.4
  include:
    - php: 7.2
      env: COVERAGE=1

services:
  - mongodb
  - mysql

install:
  - .travis/install.sh

script:
  - .travis/run.sh
